<a href="https://colab.research.google.com/github/FernandoAltamirano/sistemas-inteligentes/blob/main/Planificaci%C3%B3n_de_la_tasa_de_aprendizaje_con_disminuci%C3%B3n_basada_en_ca%C3%ADdas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
from pandas import read_csv
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import gradient_descent_v2
from sklearn.preprocessing import LabelEncoder
from keras.callbacks import LearningRateScheduler

# Planificación de la tasa de aprendizaje con disminución basada en caídas

In [21]:
dataframe = read_csv("cd.csv", header=0)
datos = dataframe.values

In [22]:
dataframe.head()

,Unnamed: 0,WTT,PTI,EQW,SBI,LQE,QWG,FDJ,PJF,HQE,NXJ,TARGET CLASS
0,0,0.913917,1.162073,0.567946,0.755464,0.780862,0.352608,0.759697,0.643798,0.879422,1.231409,1
1,1,0.635632,1.003722,0.535342,0.825645,0.924109,0.648450,0.675334,1.013546,0.621552,1.492702,0
2,2,0.721360,1.201493,0.921990,0.855595,1.526629,0.720781,1.626351,1.154483,0.957877,1.285597,0
3,3,1.234204,1.386726,0.653046,0.825624,1.142504,0.875128,1.409708,1.380003,1.522692,1.153093,1
4,4,1.279491,0.949750,0.627280,0.668976,1.232537,0.703727,1.115596,0.646691,1.463812,1.419167,1

In [23]:
dataframe.pop("Unnamed: 0")

0        0
1        1
2        2
3        3
4        4
      ...
995    995
996    996
997    997
998    998
999    999
Name: Unnamed: 0, Length: 1000, dtype: int64

In [24]:
dataframe.head()

,WTT,PTI,EQW,SBI,LQE,QWG,FDJ,PJF,HQE,NXJ,TARGET CLASS
0,0.913917,1.162073,0.567946,0.755464,0.780862,0.352608,0.759697,0.643798,0.879422,1.231409,1
1,0.635632,1.003722,0.535342,0.825645,0.924109,0.648450,0.675334,1.013546,0.621552,1.492702,0
2,0.721360,1.201493,0.921990,0.855595,1.526629,0.720781,1.626351,1.154483,0.957877,1.285597,0
3,1.234204,1.386726,0.653046,0.825624,1.142504,0.875128,1.409708,1.380003,1.522692,1.153093,1
4,1.279491,0.949750,0.627280,0.668976,1.232537,0.703727,1.115596,0.646691,1.463812,1.419167,1

In [25]:
# planificacion de tasa de aprendizaje
def paso_decaimiento(epoca):
  tasa_apre_ini = 0.1
  disminucion = 0.5 # disminución al 50%
  epocas_dis = 10.0
  tasa_apre = tasa_apre_ini * math.pow(disminucion,
  math.floor((1+epoca)/epocas_dis))
  return tasa_apre

In [26]:
X = datos[:,0:10].astype(float)
Y = datos[:,10]

In [27]:
codificador = LabelEncoder()
codificador.fit(Y)
Y = codificador.transform(Y)

In [28]:
# creacion del modelo
modelo = Sequential()
modelo.add(Dense(35, input_dim=10, activation='relu'))
modelo.add(Dense(1, activation='sigmoid'))

In [29]:
#compilar modelo
sgd = gradient_descent_v2.SGD(learning_rate=0.0,momentum=0.9)
modelo.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])

In [30]:
# callback de planificacion de aprendizaje
tasa_aprendizaje = LearningRateScheduler(paso_decaimiento)
lista_callbacks = [tasa_aprendizaje]

In [31]:
# entrenar modelo
modelo.fit(X, Y, validation_split=0.33, epochs=50, batch_size=28, callbacks=lista_callbacks, verbose=2)

Epoch 1/50
24/24 - 0s - loss: nan - accuracy: 0.0000e+00 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.1000 - 479ms/epoch - 20ms/step
Epoch 2/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.1000 - 50ms/epoch - 2ms/step
Epoch 3/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.1000 - 48ms/epoch - 2ms/step
Epoch 4/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.1000 - 70ms/epoch - 3ms/step
Epoch 5/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.1000 - 70ms/epoch - 3ms/step
Epoch 6/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.1000 - 85ms/epoch - 4ms/step
Epoch 7/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.1000 - 71ms/epoch - 3ms/step
Epoch 8/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.1000 - 97ms/epoch - 4ms/step
Epoch 9/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.1000 - 81ms/epoch - 3ms/step
Epoch 10/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0500 - 82ms/epoch - 3ms/step
Epoch 11/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0500 - 64ms/epoch - 3ms/step
Epoch 12/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0500 - 63ms/epoch - 3ms/step
Epoch 13/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0500 - 59ms/epoch - 2ms/step
Epoch 14/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0500 - 58ms/epoch - 2ms/step
Epoch 15/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0500 - 85ms/epoch - 4ms/step
Epoch 16/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0500 - 60ms/epoch - 3ms/step
Epoch 17/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0500 - 64ms/epoch - 3ms/step
Epoch 18/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0500 - 50ms/epoch - 2ms/step
Epoch 19/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0500 - 66ms/epoch - 3ms/step
Epoch 20/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0250 - 68ms/epoch - 3ms/step
Epoch 21/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0250 - 67ms/epoch - 3ms/step
Epoch 22/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0250 - 52ms/epoch - 2ms/step
Epoch 23/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0250 - 63ms/epoch - 3ms/step
Epoch 24/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0250 - 50ms/epoch - 2ms/step
Epoch 25/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0250 - 61ms/epoch - 3ms/step
Epoch 26/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0250 - 62ms/epoch - 3ms/step
Epoch 27/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0250 - 55ms/epoch - 2ms/step
Epoch 28/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0250 - 58ms/epoch - 2ms/step
Epoch 29/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0250 - 46ms/epoch - 2ms/step
Epoch 30/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0125 - 51ms/epoch - 2ms/step
Epoch 31/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0125 - 46ms/epoch - 2ms/step
Epoch 32/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0125 - 62ms/epoch - 3ms/step
Epoch 33/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0125 - 69ms/epoch - 3ms/step
Epoch 34/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0125 - 82ms/epoch - 3ms/step
Epoch 35/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0125 - 66ms/epoch - 3ms/step
Epoch 36/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0125 - 162ms/epoch - 7ms/step
Epoch 37/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0125 - 55ms/epoch - 2ms/step
Epoch 38/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0125 - 66ms/epoch - 3ms/step
Epoch 39/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0125 - 83ms/epoch - 3ms/step
Epoch 40/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0063 - 62ms/epoch - 3ms/step
Epoch 41/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0063 - 57ms/epoch - 2ms/step
Epoch 42/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0063 - 57ms/epoch - 2ms/step
Epoch 43/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0063 - 46ms/epoch - 2ms/step
Epoch 44/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0063 - 50ms/epoch - 2ms/step
Epoch 45/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0063 - 59ms/epoch - 2ms/step
Epoch 46/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0063 - 59ms/epoch - 2ms/step
Epoch 47/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0063 - 59ms/epoch - 2ms/step
Epoch 48/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0063 - 51ms/epoch - 2ms/step
Epoch 49/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0063 - 65ms/epoch - 3ms/step
Epoch 50/50
24/24 - 0s - loss: nan - accuracy: 0.0015 - val_loss: nan - val_accuracy: 0.0000e+00 - lr: 0.0031 - 120ms/epoch - 5ms/step